config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'
  #devise models
  devise_for :users, :skip => [:registration]
  devise_for :admins, :skip => [:registration]
  #site routes
  get "quem-somos", to: "site#about", as: "quem-somos"
  get "laudos-a-distancia", to: "site#report", as: "laudos-distancia"
  get "casos-clinicos", to: "site#cases", as: "casos-clinicos"
  get "fale-conosco", to: "site#contact", as: "fale-conosco"
  get "contratos", to: "contracts#index", as: "contratos"
  get "enviar-contrato", to: "contracts#upload", as: "enviar-contratos"

  #devise_for :admins
  namespace :admin do
    root to: "dashboard#index"
    resources :admins, path: "users"
    resources :reports
    resources :staffs
    resources :companies
    resources :partners
    resources :sliders
    resources :solutions
    resources :blocks
    resources :pages
    resources :cases
    resources :structures
    resources :case_attachments
    resources :users, path: "clients"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/block.rb
class Block < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
    belongs_to :page

    enum position: [:inicio, :meio, :fim]
end

app/models/case.rb
class Case < ApplicationRecord
  has_many :case_attachments
  accepts_nested_attributes_for :case_attachments
  enum status: [:publicado, :despublicado]
end

app/models/company.rb
class Company < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :logo, AvatarUploader
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :blocks
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
end

app/models/partner.rb
class Partner < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :logo, AvatarUploader
end

app/models/report.rb
class Report < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :hero_image, AvatarUploader
end

app/models/slider.rb
class Slider < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :hero_image, AvatarUploader
end

app/models/solution.rb
class Solution < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  #mount_uploader :photo, AvatarUploader
end

app/models/staff.rb
class Staff < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :photo, AvatarUploader
end

app/models/structure.rb
class Structure < ApplicationRecord
  enum status: [:publicado, :despublicado]
  mount_uploader :photo, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         enum usertype: [:fisica, :juridica]
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admins/_form.html.erb
<%= simple_form_for([:admin, @admin], wrapper: "horizontal_form", :html=> { class: 'form-horizontal form-label-left' }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :name, placeholder: "Nome Completo" %>
  <%= f.input :email, placeholder: "Endereço de Email" %>
  <%= f.input :password, placeholder: "Senha" %>
  <%= f.input :password_confirmation, placeholder: "Confirmação de Senha" %>
  <!-- <%= f.input :avatar %> -->
<div class="form-group">
  <%= f.label :avatar, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
  <div class="col-md-6 col-sm-6 col-xs-12">
     <div class="fileinput fileinput-new" data-provides="fileinput">
        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
          <%= image_tag(@admin.avatar.small.url) if @admin.avatar? %>
        </div>
        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
        <div>
          <span class="btn btn-default btn-file">
            <span class="fileinput-new">Selecionar Imagem</span>
            <span class="fileinput-exists">Alterar</span>
            <%= f.file_field :avatar %></span>
            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
        </div>
      </div>
    </div>
</div>
<div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= link_to 'Cancel', admin_admins_path, class: "btn btn-primary" %>
      <%= f.button :submit, class: "btn btn-success" do %>
        Enviar
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/admins/edit.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Editar Administrador</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Formulário</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
      <%= render 'form', admin: @admin %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/index.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Administradores</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Lista de Administradores</h2>
          <ul class="nav navbar-right">
            <li><%= button_to new_admin_admin_path, method: :get, class: "btn btn-round btn-primary" do %>
                <i class="fa fa-plus"></i> Novo Administrador
              <% end %></li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table class="table table-striped projects">
            <thead>
              <tr>
                <th style="width: 1%">#</th>
                <th style="width: 20%">Nome</th>
                <th>Email</th>
                <th>Avatar</th>
                <th>Cadastrado em:</th>
                <th style="width: 15%">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @admins.each do |admin| %>
              <tr>
                <td><%= admin.id %></td>
                <td><%= admin.name %></td>
                <td><%= admin.email %></td>
                <td>
                  <ul class="list-inline">
                    <li>
                      <% if admin.avatar? %>
                      <img src="<%= admin.avatar.thumb%>" class="avatar" alt="<%= admin.name %>">
                      <% else %>
                      <img src="/sprites/empty-avatar.jpg" class="avatar" alt="<%= admin.name %>">
                      <% end %>
                    </li>
                  </ul>
                </td>
                <td><%= admin.created_at %></td>
                <td>
                  <!-- <%= link_to '<i class="fa fa-eye"></i> Show'.html_safe, [:admin, admin], class: "btn btn-primary btn-xs" %> -->
                  <%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_admin_admin_path(admin), class: "btn btn-info btn-xs" %>
                  <%= link_to '<i class="fa fa-trash-o"></i> Excluir'.html_safe, [:admin, admin], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <!-- end project list -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/new.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Novo Administrador</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Formulário</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= render 'form', admin: @admin %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @admin.password_confirmation %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @admin.avatar %>
</p>

<%= link_to 'Edit', edit_admin_admin_path(@admin) %> |
<%= link_to 'Back', admin_admins_path %>

app/views/admin/pages/_form.html.erb
<%= simple_form_for([:admin, @page]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :status, collection: Page.statuses.keys,
                :selected => Page.statuses.keys[@page[:status].to_i],
                input_html: { autocomplete: 'off' },
                label_method: lambda {|k| k.humanize} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', [:admin, @page] %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.status %></td>
        <td><%= page.slug %></td>
        <td><%= link_to 'Show', [:admin, page] %></td>
        <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
        <td><%= link_to 'Destroy', [:admin, page], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @page.status %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>