config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'
  #devise models
  devise_for :users, :skip => [:registration]
  devise_for :admins, :skip => [:registration]
  #site routes
  get "quem-somos", to: "site#about", as: "quem-somos"
  get "laudos-a-distancia", to: "site#report", as: "laudos-distancia"
  get "casos-clinicos", to: "site#cases", as: "casos-clinicos"
  get "fale-conosco", to: "site#contact", as: "fale-conosco"
  get "contratos", to: "contracts#index", as: "contratos"
  get "enviar-contrato", to: "contracts#upload", as: "enviar-contratos"

  #devise_for :admins
  namespace :admin do
    root to: "dashboard#index"
    resources :admins, path: "users"
    resources :reports
    resources :staffs
    resources :companies
    resources :partners
    resources :sliders
    resources :solutions
    resources :blocks
    resources :pages
    resources :cases
    resources :structures
    resources :case_attachments
    resources :users, path: "clients"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/block.rb
class Block < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
    belongs_to :page

    enum position: [:inicio, :meio, :fim]
end

app/models/case.rb
class Case < ApplicationRecord
  has_many :case_attachments
  accepts_nested_attributes_for :case_attachments
  enum status: [:publicado, :despublicado]
end

app/models/case_attachment.rb
class CaseAttachment < ApplicationRecord
  mount_uploader :photo, AvatarUploader
   belongs_to :case
end

app/models/company.rb
class Company < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :logo, AvatarUploader
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :blocks
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
end

app/models/partner.rb
class Partner < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :logo, AvatarUploader
end

app/models/report.rb
class Report < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :hero_image, AvatarUploader
end

app/models/slider.rb
class Slider < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :hero_image, AvatarUploader
end

app/models/solution.rb
class Solution < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  #mount_uploader :photo, AvatarUploader
end

app/models/staff.rb
class Staff < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :photo, AvatarUploader
end

app/models/structure.rb
class Structure < ApplicationRecord
  enum status: [:publicado, :despublicado]
  mount_uploader :photo, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         enum usertype: [:fisica, :juridica]
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to admin_reports_path, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @report] }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to admin_reports_path, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @report] }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to admin_reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :content, :hero_image, :slug, :status)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/reports/_form.html.erb
<%= simple_form_for([:admin, @report], wrapper: "horizontal_form", :html=> { class: 'form-horizontal form-label-left' }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :title, placeholder: "Titulo" %>
  <%= f.input :content, placeholder: "Descrição", :input_html => {:rows => 8} %>

<div class="form-group">
  <%= f.label :hero_image, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
  <div class="col-md-6 col-sm-6 col-xs-12">
     <div class="fileinput fileinput-new" data-provides="fileinput">
        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
          <%= image_tag(@report.hero_image.small.url) if @report.hero_image? %>
        </div>
        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
        <div>
          <span class="btn btn-default btn-file">
            <span class="fileinput-new">Selecionar Imagem</span>
            <span class="fileinput-exists">Alterar</span>
            <%= f.file_field :hero_image %></span>
            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
        </div>
      </div>
    </div>
</div>

<%= f.input :status, collection: Report.statuses.keys,
            :selected => Report.statuses.keys[@report[:status].to_i],
            input_html: { autocomplete: 'off' },
            label_method: lambda {|k| k.humanize} %>

<div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= link_to 'Cancel', admin_reports_path, class: "btn btn-primary" %>
      <%= f.button :submit, class: "btn btn-success" do %>
        Enviar
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/reports/edit.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Editar Laudo</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Formulário</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= render 'form', report: @report %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/index.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Laudos a Distância</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Lista de Laudos</h2>
          <ul class="nav navbar-right">
            <li><%= button_to new_admin_report_path, method: :get, class: "btn btn-round btn-primary" do %>
                <i class="fa fa-plus"></i> Novo Laudo
              <% end %></li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table class="table table-striped projects">
            <thead>
              <tr>
                <th style="width: 1%">#</th>
                <th style="width: 20%">Título</th>
                <th>Descrição</th>
                <th>Imagem</th>
                <th>Cadastrado em:</th>
                <th style="width: 15%">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @reports.each do |report| %>
              <tr>
                <td><%= report.id %></td>
                <td><%= report.title %></td>
                <td><%= truncate report.content %></td>
                <td>
                  <ul class="list-inline">
                    <li>
                      <% if report.hero_image? %>
                      <img src="<%= report.hero_image.thumb%>" class="avatar" alt="<%= report.title %>">
                      <% else %>
                      <img src="/sprites/empty-avatar.jpg" class="avatar" alt="<%= report.title %>">
                      <% end %>
                    </li>
                  </ul>
                </td>
                <td><%= report.created_at %></td>
                <td>
                  <!-- <%= link_to '<i class="fa fa-eye"></i> Show'.html_safe, [:admin, report], class: "btn btn-primary btn-xs" %> -->
                  <%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_admin_report_path(report), class: "btn btn-info btn-xs" %>
                  <%= link_to '<i class="fa fa-trash-o"></i> Excluir'.html_safe, [:admin, report], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <!-- end project list -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/new.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Novo Laudo</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Formulário</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= render 'form', report: @report %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @report.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @report.content %>
</p>

<p>
  <strong>Hero image:</strong>
  <%= @report.hero_image %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @report.slug %>
</p>

<p>
  <strong>Status:</strong>
  <%= @report.status %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>