config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'
  #devise models
  devise_for :users, :skip => [:registration]
  devise_for :admins, :skip => [:registration]
  #site routes
  get "quem-somos", to: "site#about", as: "quem-somos"
  get "laudos-a-distancia", to: "site#report", as: "laudos-distancia"
  get "casos-clinicos", to: "site#cases", as: "casos-clinicos"
  get "fale-conosco", to: "site#contact", as: "fale-conosco"
  get "contratos", to: "contracts#index", as: "contratos"
  get "enviar-contrato", to: "contracts#upload", as: "enviar-contratos"

  #devise_for :admins
  namespace :admin do
    root to: "dashboard#index"
    resources :admins, path: "users"
    resources :reports
    resources :staffs
    resources :companies
    resources :partners
    resources :sliders
    resources :solutions
    resources :blocks
    resources :pages
    resources :cases
    resources :structures
    resources :case_attachments
    resources :users, path: "clients"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/block.rb
class Block < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
    belongs_to :page

    enum position: [:inicio, :meio, :fim]
end

app/models/case.rb
class Case < ApplicationRecord
  has_many :case_attachments
  accepts_nested_attributes_for :case_attachments
  enum status: [:publicado, :despublicado]
end

app/models/case_attachment.rb
class CaseAttachment < ApplicationRecord
  mount_uploader :photo, AvatarUploader
   belongs_to :case
end

app/models/company.rb
class Company < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :logo, AvatarUploader
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :blocks
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
end

app/models/partner.rb
class Partner < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :logo, AvatarUploader
end

app/models/report.rb
class Report < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :hero_image, AvatarUploader
end

app/models/slider.rb
class Slider < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :hero_image, AvatarUploader
end

app/models/solution.rb
class Solution < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  enum status: [:publicado, :despublicado]
  #mount_uploader :photo, AvatarUploader
end

app/models/staff.rb
class Staff < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  enum status: [:publicado, :despublicado]
  mount_uploader :photo, AvatarUploader
end

app/models/structure.rb
class Structure < ApplicationRecord
  enum status: [:publicado, :despublicado]
  mount_uploader :photo, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         enum usertype: [:fisica, :juridica]
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /partners
  # GET /partners.json
  def index
    @users = User.all
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @user = User.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners
  # POST /partners.json
  def create

    generate_password = Devise.friendly_token.first(8)

    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user][:password] = generate_password
      params[:user][:password_confirmation] = generate_password
    end
    @user = User.new(user_params)

    puts "################################################################################"
    puts "################################################################################"
    puts "################################################################################"
    puts generate_password
    puts "################################################################################"
    puts "################################################################################"
    puts "################################################################################"

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: "Cliente (#{@user.name}), foi cadastrado com sucesso!" }
        format.json { render :show, status: :created, location: [:admin, @user] }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @user.update(admin_params)
        format.html { redirect_to admin_users_path, notice: "Administrador (#{@user.name}), foi alterado com sucesso!" }
        format.json { render :show, status: :ok, location: [:admin, @user] }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "Administrador (#{@user.name}), foi excluido com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :usertype, :company, :document, :address, :number, :neighborhood, :city, :state)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for([:admin, @user], wrapper: "horizontal_form", :html=> { class: 'form-horizontal form-label-left' }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :usertype, collection: User.usertypes.keys,
  :selected => User.usertypes.keys[@user[:usertype].to_i],
  input_html: { autocomplete: 'off' },
  label_method: lambda {|k| k.humanize} %>

  <%= f.input :name, placeholder: "Nome Completo" %>
  <%= f.input :email, placeholder: "Endereço de Email" %>
  <%= f.input :company, placeholder: "Nome da Empresa" %>
  <%= f.input :document, placeholder: "CPF/CNPJ" %>
  <%= f.input :address, placeholder: "Endereço" %>
  <%= f.input :number, placeholder: "Numero" %>
  <%= f.input :neighborhood, placeholder: "Bairro" %>
  <%= f.input :city, placeholder: "Cidade" %>
  <%= f.input :state, placeholder: "Piauí" %>

<div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= link_to 'Cancel', admin_admins_path, class: "btn btn-primary" %>
      <%= f.button :submit, class: "btn btn-success" do %>
        Enviar
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Editar Administrador</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Formulário</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
      <%= render 'form', admin: @admin %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Clientes</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Lista de Clientes</h2>
          <ul class="nav navbar-right">
            <li><%= button_to new_admin_user_path, method: :get, class: "btn btn-round btn-primary" do %>
                <i class="fa fa-plus"></i> Novo Cliente
              <% end %></li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table class="table table-striped projects">
            <thead>
              <tr>
                <th style="width: 1%">#</th>
                <th style="width: 20%">Nome</th>
                <th>Email</th>
                <th>Cadastrado em:</th>
                <th style="width: 15%">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.created_at %></td>
                <td>
                  <!-- <%= link_to '<i class="fa fa-eye"></i> Show'.html_safe, [:admin, user], class: "btn btn-primary btn-xs" %> -->
                  <%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_admin_user_path(user), class: "btn btn-info btn-xs" %>
                  <%= link_to '<i class="fa fa-trash-o"></i> Excluir'.html_safe, [:admin, user], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <!-- end project list -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Novo Cliente</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <%= render "layouts/shared_admin/search" %>
      </div>
    </div>
  </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Formulário</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= render 'form', user: @user %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @admin.password_confirmation %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @admin.avatar %>
</p>

<%= link_to 'Edit', edit_admin_admin_path(@admin) %> |
<%= link_to 'Back', admin_admins_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>